<?xml version="1.0" encoding="utf-8"?>
<<<<<<< HEAD

<!-- Activity-5 -->
<!DOCTYPE products [
  <!ELEMENT products (product+)>
  <!ELEMENT product (productName, manufacturer, description?, price*, productItems )>
  <!ELEMENT productName (#PCDATA)>
  <!ELEMENT description (#PCDATA)>
  <!ELEMENT manufacturer (#PCDATA)>
  <!ELEMENT price (#PCDATA)>
  <!ELEMENT productItems (#PCDATA)>
]>
<products>
  <product>
    <productName>Dog Shirt Gift Basket</productName>
    <manufacturer>SJB Pet BoutiqueSYMBOLHERE</manufacturer>
    <description>Something for every day of the week</description>
    
      <price>US$35.99</price>
      <price>CAD$44.99</price>
      <price>&#8364;26.79</price>
    
    <productItems>1200, 1201, 1202, 1203, 1204, 1205, 1206</productItems>
  </product>
  <product>
    <productName>Car Curiosity Basket</productName>
=======
<products>
  <product>
    <product Name>Dog Shirt Gift Basket</product Name>
    <manufacturer>SJB Pet BoutiqueSYMBOLHERE</manufacturer>
    <description>Something for every day of the week</description>
    <price>US$35.99</price>
    <price>CAD$44.99</price>
    <price>&#8364;26.79</price>
    <productItems>1200, 1201, 1202, 1203, 1204, 1205, 1206</productItems>
  </product>
  <product>
    <product Name>Car Curiosity Basket</product Name>
>>>>>>> 0ac26bd13ad538629cbb77bfcab68e8597a65ec8
    <manufacturer>SJB Pet BoutiqueSYMBOLHERE</manufacturer>
    <description>Playtime morning, noon, and night</description>
    <price>US$15.99</price>
    <price>CAD$18.82</price>
    <price>&#8364;11.90</price>
    <productItems>4430, 6500, 4434</productItems>
  </product>
  <product>
<<<<<<< HEAD
    <productName>Piggy Snuggle Basket</productName>
=======
    <product Name>Piggy Snuggle Basket</product Name>
>>>>>>> 0ac26bd13ad538629cbb77bfcab68e8597a65ec8
    <manufacturer>ACMESYMBOLHERE</manufacturer>
    <price>US$17.50</price>
    <price>CAD$21.96</price>
    <price>&#8364;13.03</price>
    <productItems>3230, 3232</productItems>
  </product>
  <product>
<<<<<<< HEAD
    <productName>Dog Snuggle Basket</productName>
=======
    <product Name>Dog Snuggle Basket</product Name>
>>>>>>> 0ac26bd13ad538629cbb77bfcab68e8597a65ec8
    <manufacturer>ACMESYMBOLHERE</manufacturer>
    <price>US$14.25</price>
    <price>CAD$17.88</price>
    <price>&#8364;10.61</price>
    <productItems>3230, 3232, 3250</productItems>
  </product>
</products>